// This file was auto-generated by prisma-generator-typescript-interfaces

export type AccountState = "EMAIL_VERIFICATION" | "DOCUMENT_VERIFICATION" | "VERIFIED" | "DISABLED";

export type CardState = "ACTIVE" | "BLOCKED";

export interface User {
  id: string;
  email: string;
  login: string;
  password: string | null;
  firstName: string;
  lastName: string;
  dadName: string;
  accountState: AccountState;
  card?: Card | null;
  application?: Application[];
  EmailCode?: EmailCode[];
}

export interface Card {
  id: string;
  balance: number;
  expiration: string;
  permanentAccountNumber: string;
  userId: string;
  user?: User;
  transaction?: Transaction[];
  lastToken: string;
}

export interface Institution {
  id: string;
  name: string;
  transactionsAccepted?: Transaction[];
}

export interface Transaction {
  id: string;
  amount: number;
  date: string;
  toInstitution?: Institution;
  card?: Card;
  cardId: string;
  institutionId: string;
}

export interface Application {
  id: string;
  User?: User | null;
  userId: string | null;
}

export interface EmailCode {
  id: string;
  User?: User | null;
  userId: string | null;
  code: string;
  isActivated: boolean;
}
